### ISSUE TITLE
Blocking IPs

### ISSUE THREAD

**Issue by ads1230** [mcchas/g2h-camera-mods#6]
Hey! 

I was looking at the hostname file 

You block a load of IPs, could these go into the etc/hosts file instead? Or was there a particular reason you put them where you did?

**Comment by mcchas** [comment]
The hosts file can only work with host names or DNS names where as the camera binary has hard coded IP addresses - that's the reason I did it this way. It's a little more paranoia than anything as when watching the network traffic (after applying the changes) the camera never tried to reach an outside network. You could achieve the same with the route command instead of patching the binary.
